import { useCallback, useMemo } from "react";
import { status, launchTypes } from "@/lib/constants";
import { getProjectColumns } from "@/columnDefs/projectDef";
import DataTable from "@/components/ui/shared/datatable/datatable";

const Projects = () => {
  const projects = [
    {
      id: "972",
      launch_type: "Launch Soon",
      title: "W Residences",
      area: "Dubai Harbour",
      developer: "Arada",
      starting_price: "4300000",
      payment_plan: "60/40",
      active: "1",
      position: "99999",
    },
    {
      id: "971",
      launch_type: "New Launch",
      title: "Ghaf Woods",
      area: "Dubailand",
      developer: "Majid al Futtaim ",
      starting_price: "1200000",
      payment_plan: "60/40",
      active: "1",
      position: "99999",
    },
    {
      id: "970",
      launch_type: "New Launch",
      title: "Verve",
      area: "City Walk",
      developer: "Meraas",
      starting_price: "2210000",
      payment_plan: "75/25",
      active: "1",
      position: "1",
    },
    {
      id: "969",
      launch_type: "Launch Soon",
      title: "Al Danah Residential Tower",
      area: "Al Marjan Island",
      developer: "Dubai Investment Realestate",
      starting_price: "2100000",
      payment_plan: "70/30",
      active: "0",
      position: "99999",
    },
    {
      id: "968",
      launch_type: "Launch Soon",
      title: "Al Danah Residential Tower",
      area: "Al Marjan Island",
      developer: "Dubai Investment Realestate",
      starting_price: "2100000",
      payment_plan: "60/40",
      active: "1",
      position: "1",
    },
    {
      id: "967",
      launch_type: "Launch Soon",
      title: "Edge by Rak Properties",
      area: "Mina Al Arab",
      developer: "RAK Properties",
      starting_price: "750000",
      payment_plan: "60/40",
      active: "1",
      position: "1",
    },
    {
      id: "966",
      launch_type: "New Launch",
      title: "Golf lane",
      area: "Emaar South",
      developer: "Emaar",
      starting_price: "4480000",
      payment_plan: "80/20",
      active: "1",
      position: "1",
    },
    {
      id: "965",
      launch_type: "New Launch",
      title: "Keturah Reserve",
      area: "MBR (Mohammed Bin Rashid City)",
      developer: "MAG",
      starting_price: "2700000",
      payment_plan: "60/40",
      active: "1",
      position: "1",
    },
    {
      id: "964",
      launch_type: "Launch Soon",
      title: "VYB at Business Bay",
      area: "Business Bay",
      developer: "Ginco Properties",
      starting_price: "1280000",
      payment_plan: "40/60",
      active: "1",
      position: "2",
    },
    {
      id: "963",
      launch_type: "Launch Soon",
      title: "Arlo By Emaar",
      area: "Dubai Creek Harbour",
      developer: "Emaar",
      starting_price: "1700000",
      payment_plan: "70/30",
      active: "1",
      position: "2",
    },
    {
      id: "962",
      launch_type: "Launch Soon",
      title: "Tiger Sky Tower",
      area: "Business Bay",
      developer: "Tiger Group",
      starting_price: "2200000",
      payment_plan: "70/30",
      active: "1",
      position: "2",
    },
    {
      id: "961",
      launch_type: "Launch Soon",
      title: "Elie Saab Waterfront",
      area: "Shams Abu Dhabi",
      developer: "DECA Properties",
      starting_price: "2000000",
      payment_plan: "90/10",
      active: "1",
      position: "3",
    },
    {
      id: "960",
      launch_type: "Launch Soon",
      title: "One B by Wasl",
      area: "Al Quoz",
      developer: "Wasl",
      starting_price: "1600000",
      payment_plan: "40/60",
      active: "1",
      position: "3",
    },
    {
      id: "959",
      launch_type: "Launch Soon",
      title: "Dubai Harbour Residences",
      area: "Dubai Creek Harbour",
      developer: "H&H",
      starting_price: "3900000",
      payment_plan: "60/40",
      active: "1",
      position: "1",
    },
    {
      id: "958",
      launch_type: "New Launch",
      title: "Skyscape Avenue",
      area: "Sobha Hartland",
      developer: "Sobha",
      starting_price: "1698573",
      payment_plan: "70/30",
      active: "1",
      position: "1",
    },
    {
      id: "957",
      launch_type: "Launch Soon",
      title: "Masa Residence",
      area: "Al Marjan Island",
      developer: "Durar Group",
      starting_price: "0",
      payment_plan: "50/50",
      active: "1",
      position: "3",
    },
    {
      id: "956",
      launch_type: "Launch Soon",
      title: "Project by Ellington Properties",
      area: "Meydan",
      developer: "Ellington Properties",
      starting_price: "0",
      payment_plan: "70/30",
      active: "1",
      position: "3",
    },
    {
      id: "955",
      launch_type: "Hot Projects",
      title: "One by Binghatti",
      area: "Business Bay",
      developer: "Binghatti",
      starting_price: "1699999",
      payment_plan: "70/30",
      active: "1",
      position: "3",
    },
    {
      id: "954",
      launch_type: "New Launch",
      title: "Baccarat Tower",
      area: "Downtown Dubai",
      developer: "H&H",
      starting_price: "22000000",
      payment_plan: "60/40",
      active: "1",
      position: "4",
    },
    {
      id: "953",
      launch_type: "Launch Soon",
      title: "Raya in Jebel Sifah",
      area: " Muscat (The Sultanate of Oman)",
      developer: "Muriya",
      starting_price: "1800000",
      payment_plan: "In Process",
      active: "0",
      position: "4",
    },
    {
      id: "952",
      launch_type: "Launch Soon",
      title: "Ela Residences",
      area: "Palm Jumeirah",
      developer: "Omniyat",
      starting_price: "0",
      payment_plan: "60/40",
      active: "1",
      position: "4",
    },
    {
      id: "951",
      launch_type: "Launch Soon",
      title: "Kempinski Marina Residences",
      area: "Dubai Marina",
      developer: " ABA Group",
      starting_price: "2200000",
      payment_plan: "60/40",
      active: "1",
      position: "1",
    },
    {
      id: "950",
      launch_type: "Launch Soon",
      title: "Palace Residences Dubai Hills Estate",
      area: "Dubai Hills",
      developer: "Emaar",
      starting_price: "1760000",
      payment_plan: "80/20",
      active: "1",
      position: "5",
    },
    {
      id: "949",
      launch_type: "Launch Soon",
      title: "The Heights Country Club and Wellness",
      area: "Dubai Investment Park",
      developer: "Emaar",
      starting_price: "0",
      payment_plan: "In Process",
      active: "1",
      position: "6",
    },
    {
      id: "948",
      launch_type: "Launch Soon",
      title: "Grand Polo Club and Resort",
      area: "Dubai Investment Park",
      developer: "Emaar",
      starting_price: "0",
      payment_plan: "70/30",
      active: "1",
      position: "7",
    },
    {
      id: "947",
      launch_type: "Launch Soon",
      title: "Riverside",
      area: "Dubai Investment Park",
      developer: "Damac",
      starting_price: "1900000",
      payment_plan: "70/30",
      active: "1",
      position: "8",
    },
  ];
  const searchCriteria = [
    {
      name: "title",
      title: "Title",
    },
    {
      name: "area",
      title: "Area",
    },
    {
      name: "developer",
      title: "Developer",
    },
  ];
  const filterCriteria = [
    {
      name: "active",
      title: "Status",
      options: status,
    },
    {
      name: "launch_type",
      title: "Launch Type",
      options: launchTypes,
    },
  ];

  const onEdit = useCallback(
    (project: ProjectProps) => console.log(`Edited ${project.title}`),
    []
  );
  const onDelete = useCallback(
    (project: ProjectProps) => console.log(`Deleted ${project.title}`),
    []
  );
  const projectColumns = useMemo(
    () => getProjectColumns({ onEdit, onDelete }),
    []
  );

  return (
    <DataTable
      search={searchCriteria}
      filters={filterCriteria}
      columns={projectColumns}
      data={projects}
    />
  );
};

export default Projects;
